### ISSUE TITLE
agree on license

### ISSUE THREAD

**Issue by orbeckst** [alchemistry/alchemlyb#15]
When @dotsdl started the project he used the permissive BSD 3-clause license. However, it is still early in the project and we can easily change the license at this stage. I would like to have a discussion and eventually a consensus on the license.

I tend to license any code coming out of academia under GPL, reasoning that this will in the long run create the largest benefit to the (academic) scientific eco system because it forces anyone using the code for their projects making their code available in turn under conditions that allow me (and others) to use it without restriction.

I am fully aware that not everyone agrees with this view and I had a very good general discussion with @davidlmobley on the matter already. I am inviting anyone with a stake and opinion on the matter to make their point and I hope that this will be a fruitful discussion.

**Comment by davidlmobley** [comment]
I can't elaborate in great detail now (especially since @orbeckst and I have already talked) but both @jchodera and I have industry and software company collaborators who we want to share tools with, be able to collaborate with, etc., who will have trouble with even using GPL software together with their in-house tools for IP reasons. These are people who would likely be willing to contribute to this project in some cases, or at least would be contributing to our projects which would use this project, but without it being GPL they would have to go elsewhere. 

So, permissive BSD 3-clause or MIT would work best, but GPL would be a significant problem.

**Comment by jchodera** [comment]
In general, I would love for the license to reflect the philosophy "if you make changes/improvements to the code, you should be encouraged to contribute those changes back to improve the original code". Various licenses interpret this in various different ways, but it does make things difficult if it ends up requiring someone to open-source their entire codebase if they import a module under one of these licenses---that has led some to call these licenses "parasitic". I'm a huge fan of the GPL, but realize there are constraints that actually lead to *less* adoption and use of our code (and often less interest in contributing to its development as a result).

We had previously been licensing a great deal of our code under LGPL, since we thought it struck the best balance here, but some legal interpretations seem to think that even importing LGPL modules in a Python codebase requires contributing the rest of the codebase as open source. I'm not sure this interpretation actually makes sense to me, but IANAL. As a result, the permissive MIT license has been the default recently, but I'd love for some legal clarity on what MIT vs BSD 3-clause vs LGPL might actually mean in terms of the use and modification of Python packages in particular.

**Comment by jchodera** [comment]
I also wonder, if legal interpretations are required, if the [MolSSI](http://molssi.org) has the means to retain legal representation to provide useful legal advice on this choice.

**Comment by orbeckst** [comment]
What I am *hoping* for is the spirit of open source flourishing, namely a diverse range of people using and contributing back and sharing their own advances in a way that I can use them freely. What I fear is a one-way street where academic research (in my case, funded by the NIH and thus ultimately by the tax payers) gets sucked up into commercial products without any additional gain for the academic field.

By all means, let alchemlyb be a test case. We choose a permissive license (MIT or BSD 3-clause – I don't have strong preferences). Then we'll see over time how much it actually encourages industrial partners to contribute back. I hope to be positively surprised.

@davidlmobley / @jchodera : Which licence do you want to use and we go with it.

**Comment by davidlmobley** [comment]
I like the idea of using this as a test case, @orbeckst . 

I've been using MIT lately, so would default to that, but I don't have a strong preference either.

**Comment by jchodera** [comment]
We have switched YANK to MIT, and have already had success with industry contracts that fund the further development of the open source tool. So we have empirical proof that this model can work. :)

I would honestly be much happier if we *do* find a license that requires modifications to the tool itself to be contributed back when the modified tool is distributed (which even the GPL doesn't require---GPL just requires you to give the modified source to whoever you distribute the binaries to), but without the possibility of tying up other parts of the Python framework that may be incidental to the tool into the "what must be contributed".

**Comment by davidlmobley** [comment]
Yes, I agree with John -- GPL/LGPL are after a goal we're interested in too (making sure open software advances), but they also have side effects that we don't like, such as making it hard for people to even use the software in a for-profit enterprise which involves software development without major IP worries.

In my ideal world, we would all use the same software for things like `alchemlyb` is seeking to enable, but we would be able to use it as part of whatever workflows we want without having to worry about licensing issues, and we could all contribute to its ongoing development/improvement.

I haven't done any kind of exhaustive survey, but I believe `matplotlib`, `pandas`, `dask`, and `numpy` are all BSD licensed software. `matplotlib` makes a point of highlighting that it only uses software which is compatible with the `BSD` license, which presumably means they're not drawing on anything that is GPL/LGPL.

**Comment by orbeckst** [comment]
As an aside: *requiring* any modifications to be contributed back will make the software *non-free*, at least in the eyes of the GNU project: see "The freedom to redistribute if you wish: basic requirements" in [What is free software?](https://www.gnu.org/philosophy/free-sw.html):
> You should also have the freedom to make modifications and use them privately in your own work or play, without even mentioning that they exist. If you do publish your changes, you should not be required to notify anyone in particular, or in any particular way. 

I generally agree with this statement and don't think we should try to come up with a license that would not considered free.

Do you want to use MIT or BSD-3 clause? 

* BSD-3: common in Python eco-system, currently the selected licence
* MIT: @jchodera had good experience with it

**Comment by davidlmobley** [comment]
Let's do BSD-3 given how common it is, unless there are objections. For the purposes of collaborators we have in mind the one should be as good as the other, I think.

It's a bit of an odd world where, in many cases, it would be easier for industry folks to use software and contribute their modifications back than it would be for them to "freely" use it under the terms of the GNU project.

**Comment by orbeckst** [comment]
There's one problem: https://github.com/MobleyLab/alchemical-analysis is LGPL! 

How much of that code is going to end up here? Can this be re-licensed?

**Comment by davidlmobley** [comment]
Should be able to be re-licensed, I would think -- most significant contributors are @mrshirts and myself and a former grad student who I could reach. And @halx. 

Also, I think it needs an almost total rewrite. 

We did this back before the "LGPL can cause problems" issue came on our radar.

**Comment by davidlmobley** [comment]
To be clear, my current plan was to re-write `alchemical-analysis` from scratch to use `alchemlyb` as `alchemlyb` develops, and NOT to go the other way around and re-use `alchemical-analysis` components in `alchemlyb`. @dotsdl - thoughts?

**Comment by dotsdl** [comment]
@davidlmobley agreed, I can't say I've used any of the code in ``alchemical-analysis`` so far, and I don't think I'll have to. Our data structures in ``alchemlyb`` look completely different so the implementation of even simple things like ``TI`` look completely different code-wise.

**Comment by orbeckst** [comment]
Ok, then I'm fine with BSD-3.

**Comment by mrshirts** [comment]
>  I can't say I've used any of the code in alchemical-analysis so far, and I don't think I'll have to. Our data structures in alchemlyb look completely different so the 

So I think that if you don't figure out _why_ alchemical-analysis did certain things, you'll discover that you aren't actually supporting a lot of edge cases and functionality, and will have to go back and redo a lot. I'm happy to answer any questions on any of the logic or approach (though occasionally it may take a bit of time to figure out when the code has evolved from what I originally wrote). 

I agree that the actual code final code will have very little overlap with alchemical-analysis.

**Comment by orbeckst** [comment]
Alright, then let's keep BSD-3 – if you disagree, please re-open.
