### ISSUE TITLE
CLI interface

### ISSUE THREAD

**Issue by danijoo** [alchemistry/alchemlyb#155]
I think it would be nice to have some kind of command-line interface to provide an easy access to the features of this lib for  applications, similar to what deprecated [alchemical-analysis](https://github.com/MobleyLab/alchemical-analysis) provided for python2.

Is something like this planned for a future release? Would you accept PRs going in this direction? This could also be a separate package that enhances/utilizes alchemlyb.

**Comment by orbeckst** [comment]
[flamel](https://github.com/alchemistry/flamel) is supposed to be the CLI and [successor to alchemical-analysis](https://github.com/alchemistry/alchemlyb/wiki/Roadmap#librarify-alchemical-analysis-functionality). Development has stalled due to insufficient availability of developers so _anyone_ who wants to contribute and revive the project would be most welcome!!
