### ISSUE TITLE
Build out initial test suite

### ISSUE THREAD

**Issue by orbeckst** [alchemistry/alchemlyb#2]
Minimum test suite required (probably using pytest).

**Comment by davidlmobley** [comment]
@dotsdl - did you have something in mind on this? Do you need help? 

I see you have some GROMACS parsers in here, so presumably we're ready to have some tests enabled since there is something to test?

**Comment by dotsdl** [comment]
@davidlmobley we're cooking up a test data set with benzene in water with gromacs, and I'll start building up tests around that once we have them (today or tomorrow). Perhaps it makes sense to make benzene in water (calculating a hydration free energy) the standard test system we should expect for each dataset contributed for each package we support, to make things simple (and keep things small)?

One concern I have upfront is that if we include datasets for each package we build parsers for, this could grow rather large. One option is to make the collection of test datasets a separate Python package, with `alchemlyb`'s tests using that package for source data. We could also use that package for building out runnable examples used in the documentation.

**Comment by davidlmobley** [comment]
One random thought: You possibly could make benzene in IMPLICIT water in GROMACS a fast/small enough test that it could run on Travis-CI. That might be interesting. :) 

I do like benzene in water as a standard test set. It is too simple a test for whether hydration free energy calculations are being done correctly (it's too easy to get it right) but for analysis, it should serve well.

If it grows too large, I do like the idea of making the test datasets a separate package.

**Comment by dotsdl** [comment]
Hmmm...would the implicit water one converge faster? My guess would be yes (even if it's systematically off, not a concern in this context), so that would be a good standard test case in general. Good idea!

On dataset size: I don't have a clear idea as to how big the test dataset would be once we've collected one for each package, but if we think it's over 10MB I think we should maintain these in a separate repository and ship as a separate package. Otherwise the `alchemlyb` repo itself can become a bit unwieldy.

If having things separate is more an issue than it's worth, and it's not as big as we thought, we can put them in `alchemlyb` itself. But doing the reverse is not so easy with git.

One thing @orbeckst mentioned in discussion yesterday is making parsers support decompression for `bzip` and `gzip`, which is actually easy enough to include and means that our test data can also all be compressed. I'll see what works well over the next week and report back here.

**Comment by davidlmobley** [comment]
With implicit water solvation, at least for small molecules like those in FreeSolv, you don't actually even need intermediate alchemical states -- you can just run a gas phase simulation and reprocess. Intermediate states are of course fine (er, if GROMACS now handles them properly -- otherwise you could just do lambda=0 and lambda=1 where lambda only controls charges), but it should test the basic infrastructure.

I like the idea of parsers which support compression.

**Comment by orbeckst** [comment]
With https://github.com/alchemistry/alchemtest working nicely and current 96% coverage (awesome @dotsdl !) I think this issue has been taken care of.
