### ISSUE TITLE
`statistical_inefficiency` should raise an error when not given `series`

### ISSUE THREAD

**Issue by VOD555** [alchemistry/alchemlyb#337]
The currunt `statistical_inefficiency` in `preprocessing.subsampling` will not do the subsampling when not given the `series` input and does not raise an error or any massage to show that it's not doing the job. This makes it misleading for one using it.

https://github.com/alchemistry/alchemlyb/blob/862343b7365114cef5aea82243715935f0af6e61/src/alchemlyb/preprocessing/subsampling.py#L530C10-L530C10

**Comment by xiki-tempula** [comment]
Sorry upon a closer look, this seems to be a feature which has been supported since god knows when.
When series is not provided, the statistical_inefficiency could provide a high level function that could be used to massage the data. For example, `statistical_inefficiency(unsorted, None, sort=True)` would sort the dataframe. I could however, issue an warning.
