### ISSUE TITLE
Gromacs XVG parser - Calculation of the reduced potential goes badly wrong 

### ISSUE THREAD

**Issue by harlor** [alchemistry/alchemlyb#59]
Assuming to find values of U and pV in the second and last column can go badly wrong if they are not given. 

https://github.com/alchemistry/alchemlyb/blob/e5b2e581528769a205cab17dfae7d1b9b2f8f2f5/src/alchemlyb/parsing/gmx.py#L49-L61

What do you think: Should we print a warning when these columns are not given and continue with what is given or directly throw an exception?

Btw: Is it really necessary to add pV if the simulations are in NVT? Why do we add U?

**Comment by mrshirts** [comment]
If the simulations are carried out at 2 different temperatures, we need U, as the ratio of Boltzmann factors involved the total energy, not just the difference.

Certainly, if they are not given, this should be caught well before. 

For NVT, one shouldn't need PV.  I'll need to check to see how this was handled in alchemical-analysis.

**Comment by dotsdl** [comment]
Hi @harlor, welcome to `alchemlyb`! We're always looking for ways to improve the existing components of the library. Do you have an example dataset using NVT? It would be worthwhile to generate one, perhaps with a single molecule such as [benzene](https://github.com/alchemistry/alchemtest/blob/master/src/alchemtest/gmx/benzene/descr.rst), but in NVT instead of NPT. @ianmkenney, do you have a way to do this by chance?

**Comment by harlor** [comment]
I have NPT and NVT datasets available but all without U.

If I understand the alchemical-analysis parser correctly it ads pV if its available and does not add U.

Maybe if nothing else os specified one could add pV if its available and add U if its available?
